When diagnosing overload set candidates, pass the decl into diagnose instead of the location of the decl.  This matters when the candidates are coming from the stdlib because they have no location, and we can synthesize a prototype from the decl.  Before we'd get:
t.swift:36:28: error: ambiguous reference to member 'String.init'
    return lazy.map(String.init).joinBySeparator(", ")
                    ~~~~~~~^~~~
<unknown>:0: note: found this candidate
<unknown>:0: note: found this candidate
<unknown>:0: note: found this candidate
.... 40 more of these.

Now we get:

t.swift:36:28: error: ambiguous reference to member 'String.init'
    return lazy.map(String.init).joinBySeparator(", ")
                    ~~~~~~~^~~~
Swift.String:95:3: note: found this candidate
  init()
  ^
Swift.String:96:3: note: found this candidate
  init(_ _core: _StringCore)
  ^
Swift.String:3:3: note: found this candidate
  init(_ c: Character)
  ^
Swift.String:24:3: note: found this candidate
  init(_ characters: String.CharacterView)
  ^
...



Swift SVN r31458