fix <rdar://problem/16574105> Type inference of _Nil very coherent but kind of useless
We now diagnose this as an error:

t.swift:1:5: error: variable 'x' inferred to nil with unspecified type; use a type annotation to specify which nil
var x = nil
    ^

since it is never useful to get the internal _Nil type.


Swift SVN r16223