[cxx-interop] Fix CxxStdlib build error on CentOS
This fixes a build failure that started occurring on CentOS after https://github.com/apple/swift/pull/65057:
```
error: cannot find 'strlen' in scope
```

rdar://107987115
(cherry picked from commit 7774650db1c7fbdb7527767b96c220872832f5de)