[ClangImporter] Allow access to ObjC interfaces/protocols through module containing demoted definition
When Clang loads modules, it maintains only a single prevailing
definition of various kinds of types, folding duplicate definitions
somehow. Typically before folding two definitions together, they are
compared for equality somehow, to diagnose ODR violation style issues.

Different Swift modules may be compiled with access to different clang
modules. In the presence of a duplicates Objective-C interface Foo,
defined once in ClangModuleA and again in ClangModuleB, Swift modules
compiled against only ClangModuleA will form references to
ClangModuleA.Foo and Swift modules compiled against only ClangModuleB
will form references to ClangModuleB.Foo.

If now later, all the Swift and Clang modules are loaded together,
Clang will fold ClangModuleA.Foo and ClangModuleB.Foo together, and only
one will survive. References to the module that does not survive will
then be left invalid. Without these changes, the provided test fails
with:

```
.---command stderr------------
| /Users/nuriamari/local/git/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/test-macosx-arm64/ClangImporter/Output/allow_access_through_demoted_objc_types.swift.tmp/Client.swift:7:16: error: no type named 'SharedClass' in module 'B'
|  5 |
|  6 | func useA(_: A.SharedClass) {}
|  7 | func useB(_: B.SharedClass) {}
|    |                `- error: no type named 'SharedClass' in module 'B'
|  8 | func useSwiftA(_: SwiftA.ClassFromA) {}
|  9 | func useSwiftB(_: SwiftB.ClassFromB) {}
|
| /Users/nuriamari/local/git/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/test-macosx-arm64/ClangImporter/Output/allow_access_through_demoted_objc_types.swift.tmp/SwiftB.swiftmodule:1:1: warning: reference to type 'SharedClass' broken by a context change; 'SharedClass' was expected to be in 'B', but now a candidate is found only in 'A'
| 1 | B.SharedClass
|   | |- warning: reference to type 'SharedClass' broken by a context change; 'SharedClass' was expected to be in 'B', but now a candidate is found only in 'A'
|   | |- note: the type was expected to be found in module 'B' at '/Users/nuriamari/local/git/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/test-macosx-arm64/ClangImporter/Output/allow_access_through_demoted_objc_types.swift.tmp/module.modulemap'
|   | |- note: the type was actually found in module 'A' at '/Users/nuriamari/local/git/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/test-macosx-arm64/ClangImporter/Output/allow_access_through_demoted_objc_types.swift.tmp/module.modulemap'
|   | `- note: declarations in the clang module 'B' may be hidden by clang preprocessor macros
| <unknown>:0: note: attempting to recover from the previous modularization issue
| /Users/nuriamari/local/git/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/test-macosx-arm64/ClangImporter/Output/allow_access_through_demoted_objc_types.swift.tmp/Client.swift:11:24: error: no type named 'SharedProtocol' in module 'B'
|  9 | func useSwiftB(_: SwiftB.ClassFromB) {}
| 10 | func useAProtocol(_: A.SharedProtocol) {}
| 11 | func useBProtocol(_: B.SharedProtocol) {}
|    |                        `- error: no type named 'SharedProtocol' in module 'B'
| 12 | func useSwiftAProtocol(_: SwiftA.ProtocolFromA) {}
| 13 | func useSwiftBProtocol(_: SwiftB.ProtocolFromB) {}
|
| /Users/nuriamari/local/git/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/test-macosx-arm64/ClangImporter/Output/allow_access_through_demoted_objc_types.swift.tmp/SwiftB.swiftmodule:1:1: warning: reference to type 'SharedProtocol' broken by a context change; 'SharedProtocol' was expected to be in 'B', but now a candidate is found only in 'A'
| 1 | B.SharedProtocol
|   | |- warning: reference to type 'SharedProtocol' broken by a context change; 'SharedProtocol' was expected to be in 'B', but now a candidate is found only in 'A'
|   | |- note: the type was expected to be found in module 'B' at '/Users/nuriamari/local/git/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/test-macosx-arm64/ClangImporter/Output/allow_access_through_demoted_objc_types.swift.tmp/module.modulemap'
|   | |- note: the type was actually found in module 'A' at '/Users/nuriamari/local/git/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/test-macosx-arm64/ClangImporter/Output/allow_access_through_demoted_objc_types.swift.tmp/module.modulemap'
|   | `- note: declarations in the clang module 'B' may be hidden by clang preprocessor macros
| <unknown>:0: note: attempting to recover from the previous modularization issue
`-----------------------------
error: command failed with exit status: 1
```

This changes is modelled after
https://github.com/swiftlang/swift/pull/41144 and
https://reviews.llvm.org/D118855, which make analogous changes, but for
redeclared TagDecls instead.