[Distributed] Fix swift-api-dump missing option
Resolves rdar://83727543

Without the fix we fail silly:

```
-> % ./utils/swift-api-dump.py ... 
Traceback (most recent call last):
  File "./utils/swift-api-dump.py", line 358, in <module>
    main()
  File "./utils/swift-api-dump.py", line 333, in main
    if args.enable_experimental_distributed:
AttributeError: 'Namespace' object has no attribute 'enable_experimental_distributed'
```