Revert "[Embedded] Support CoroutineAccessors in no-allocations embedded" (#91475)
Reverts swiftlang/swift#90516

To unblock nightly toolchain

```
 ******************** TEST 'Swift(linux-x86_64) :: embedded/no-allocations-coroutine-legacy.swift' FAILED ********************
01:13:01.651  Exit Code: 1
01:13:01.651  
01:13:01.651  Command Output (stdout):
01:13:01.651  --
01:13:01.651  # RUN: at line 5
01:13:01.651  not /home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend -target x86_64-unknown-linux-gnu  -module-cache-path /home/build-user/build/buildbot_linux/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache -swift-version 4  -define-availability 'SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999' -define-availability 'SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2' -define-availability 'SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0' -define-availability 'SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4' -define-availability 'SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0' -define-availability 'SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5' -define-availability 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0' -define-availability 'SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4' -define-availability 'SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0' -define-availability 'SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4' -define-availability 'SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0' -define-availability 'SwiftStdlib 5.10:macOS 14.4, iOS 17.4, watchOS 10.4, tvOS 17.4, visionOS 1.1' -define-availability 'SwiftStdlib 6.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0' -define-availability 'SwiftStdlib 6.1:macOS 15.4, iOS 18.4, watchOS 11.4, tvOS 18.4, visionOS 2.4' -define-availability 'SwiftStdlib 6.2:anyAppleOS 26.0' -define-availability 'SwiftStdlib 6.3:anyAppleOS 26.4' -define-availability 'SwiftStdlib 6.4:anyAppleOS 27.0' -define-availability 'SwiftStdlib 6.5:anyAppleOS 9999' -define-availability 'SwiftCompatibilitySpan 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2, visionOS 1.0' -define-availability 'SwiftCompatibilitySpan 6.2:macOS 26.0, iOS 26.0, watchOS 26.0, tvOS 26.0, visionOS 26.0' -define-availability 'Backtracing 6.2: macOS 26.0'  -typo-correction-limit 10 -solver-enable-diagnose-valid-salvage  -emit-ir /home/build-user/swift/test/embedded/no-allocations-coroutine-legacy.swift -enable-experimental-feature Embedded -enable-experimental-feature CoroutineAccessors -no-allocations -wmo 2>&1 | /usr/bin/python3.10 /home/build-user/swift/utils/PathSanitizingFileCheck --allow-unused-prefixes --sanitize TMP_DIR=/home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/embedded/Output/no-allocations-coroutine-legacy.swift.tmp --sanitize BUILD_DIR=/home/build-user/build/buildbot_linux/swift-linux-x86_64 --sanitize SOURCE_DIR=/home/build-user/swift --ignore-runtime-warnings --use-filecheck /home/build-user/build/buildbot_linux/llvm-linux-x86_64/bin/FileCheck   /home/build-user/swift/test/embedded/no-allocations-coroutine-legacy.swift
01:13:01.651  # executed command: not /home/build-user/build/buildbot_linux/swift-linux-x86_64/bin/swift-frontend -target x86_64-unknown-linux-gnu -module-cache-path /home/build-user/build/buildbot_linux/swift-linux-x86_64/swift-test-results/x86_64-unknown-linux-gnu/clang-module-cache -swift-version 4 -define-availability 'SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999' -define-availability 'SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2' -define-availability 'SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0' -define-availability 'SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4' -define-availability 'SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0' -define-availability 'SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5' -define-availability 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0' -define-availability 'SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4' -define-availability 'SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0' -define-availability 'SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4' -define-availability 'SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0' -define-availability 'SwiftStdlib 5.10:macOS 14.4, iOS 17.4, watchOS 10.4, tvOS 17.4, visionOS 1.1' -define-availability 'SwiftStdlib 6.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0' -define-availability 'SwiftStdlib 6.1:macOS 15.4, iOS 18.4, watchOS 11.4, tvOS 18.4, visionOS 2.4' -define-availability 'SwiftStdlib 6.2:anyAppleOS 26.0' -define-availability 'SwiftStdlib 6.3:anyAppleOS 26.4' -define-availability 'SwiftStdlib 6.4:anyAppleOS 27.0' -define-availability 'SwiftStdlib 6.5:anyAppleOS 9999' -define-availability 'SwiftCompatibilitySpan 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2, visionOS 1.0' -define-availability 'SwiftCompatibilitySpan 6.2:macOS 26.0, iOS 26.0, watchOS 26.0, tvOS 26.0, visionOS 26.0' -define-availability 'Backtracing 6.2: macOS 26.0' -typo-correction-limit 10 -solver-enable-diagnose-valid-salvage -emit-ir /home/build-user/swift/test/embedded/no-allocations-coroutine-legacy.swift -enable-experimental-feature Embedded -enable-experimental-feature CoroutineAccessors -no-allocations -wmo
01:13:01.651  # note: command had no output on stdout or stderr
01:13:01.651  # error: command failed with exit status: 1
01:13:01.651  # executed command: /usr/bin/python3.10 /home/build-user/swift/utils/PathSanitizingFileCheck --allow-unused-prefixes --sanitize TMP_DIR=/home/build-user/build/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/embedded/Output/no-allocations-coroutine-legacy.swift.tmp --sanitize BUILD_DIR=/home/build-user/build/buildbot_linux/swift-linux-x86_64 --sanitize SOURCE_DIR=/home/build-user/swift --ignore-runtime-warnings --use-filecheck /home/build-user/build/buildbot_linux/llvm-linux-x86_64/bin/FileCheck /home/build-user/swift/test/embedded/no-allocations-coroutine-legacy.swift
01:13:01.651  # .---command stderr------------
01:13:01.652  # | /home/build-user/swift/test/embedded/no-allocations-coroutine-legacy.swift:12:11: error: CHECK: expected string not found in input
01:13:01.652  # | // CHECK: error: coroutine accessor involves heap allocation [#PerformanceHints::HeapAllocation]
01:13:01.652  # |           ^
01:13:01.652  # | <stdin>:1:1: note: scanning from here
01:13:01.652  # | ; ModuleID = '<swift-imported-modules>'
01:13:01.652  # | ^
01:13:01.652  # | 
01:13:01.652  # | Input file: <stdin>
01:13:01.652  # | Check file: /home/build-user/swift/test/embedded/no-allocations-coroutine-legacy.swift
01:13:01.652  # | 
01:13:01.652  # | -dump-input=help explains the following input dump.
01:13:01.652  # | 
01:13:01.652  # | Input was:
01:13:01.652  # | <<<<<<
01:13:01.652  # |           1: ; ModuleID = '<swift-imported-modules>' 
01:13:01.652  # | check:12     X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
01:13:01.652  # |           2: source_filename = "<swift-imported-modules>" 
01:13:01.652  # | check:12     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
01:13:01.652  # |           3: target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128" 
01:13:01.652  # | check:12     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
01:13:01.652  # |           4: target triple = "x86_64-unknown-linux-gnu" 
01:13:01.652  # | check:12     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
01:13:01.652  # |           5:  
01:13:01.652  # | check:12     ~
01:13:01.652  # |           6: %swift.coro_func_pointer = type <{ i32, i32, i64 }> 
01:13:01.652  # | check:12     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
01:13:01.652  # |           .
01:13:01.652  # |           .
01:13:01.652  # |           .
01:13:01.652  # | >>>>>>
01:13:01.652  # `-----------------------------
01:13:01.652  # error: command failed with exit status: 1
01:13:01.652  
01:13:01.652  --
01:13:01.652  
01:13:01.652  ********************
```