[AutoDiff][SR-13152] Better diagnostic for `static` decl modifier mismatch.
Improved diagnostic for when the registered derivative function and
the function it derivates (the original) differ in terms of
`static` declaration modifier usage. Suggesting as well a fix-it,
to either remove or add the `static` keyword.

The registered derivative needs to be marked as `static` in two cases:

1. When the original function is a constructor.
2. When the original function is static as well.

When the original function is an instance method, the registered derivate
must be as well.

Given the following example:

```swift
struct Foo: Differentiable {
    static func sf1(_ x : Float) -> Float {
        return x * x * x
    }
}

extension Foo {
    @derivative(of: sf1)
    func vjpF1(_ x: Float) -> (value: Float, pullback: (Float.TangentVector) -> (Foo.TangentVector, Float.TangentVector)) {
        fatalError()
    }
}
```

Before this PR:
```bash
sr_13152.swift:25:21: error: referenced declaration 'sf1' could not be resolved
    @derivative(of: sf1)
                    ^
sr_13152.swift:19:17: note: candidate static method does not have expected type '(Foo) -> (Float) -> Float'
    static func sf1(_ x : Float) -> Float {
```

After this PR:
```bash
sr_13152.swift:26:10: error: function must match usege of static declaration modifier from original function 'vjpF1'
    func vjpF1(_ x: Float) -> (value: Float, pullback: (Float.TangentVector) -> (Foo.TangentVector, Float.TangentVector)) {
         ^
sr_13152.swift:26:5: note: mark the function 'vjpF1' as static
    func vjpF1(_ x: Float) -> (value: Float, pullback: (Float.TangentVector) -> (Foo.TangentVector, Float.TangentVector)) {
    ^
    static
```

Resolves [SR-13152](https://bugs.swift.org/browse/SR-13152).