Revert "[Type Checker] Extend Path Consistency algorithm to cover collections"
This reverts commit f590a1ba0332b3cee29f4c8cbf59bd73ee6d8922.

It breaks this kind of code:

test.swift:2:34: error: cannot convert value of type 'Int' to expected element type 'UInt32'
 let lengthBytes: [UInt32] = [55 * 8, 0]
                              ~~~^~~
                              UInt32( )