[cxx-interop] Do not import `std::__compressed_pair`
This type is triggering modularization issues in libc++:
```
error: definition of '__builtin_new_deleter' must be imported from module 'std_private_memory_builtin_new_allocator' before it is required
```

This is a workaround to keep things building.

rdar://142576799
(cherry picked from commit cb2bd321ce2eaf413232667c6104ade57db92247)