better QOI for invalid arguments, produce: error: unexpected diagnostic produced: error: operators must have one or two arguments func %%%() {} ^
instead of:
error: unexpected diagnostic produced: error: operators must be declared 'infix_left'
func %%%() {}
^



Swift SVN r648