test: convert the output to string
With Python 3, the regular expression match will fail due to a mismatch
in types:

```
TypeError: cannot use a string pattern on a bytes-like object
```

Convert the output to a string object.