Revert "[func-sig-opts] Teach func sig opts how to handle multiple @owned arguments."
It breaks the build:

/Users/erik/proj/main-swift/swift/lib/SILPasses/FunctionSignatureOpts.cpp:125:9: error: no template named 'reverse_iterator' in 'llvm::MapVector<unsigned int, swift::SILInstruction *, llvm::SmallDenseMap<unsigned int, unsigned int, 8, llvm::DenseMapInfo<unsigned int> >, llvm::SmallVector<std::__1::pair<unsigned int, swift::SILInstruction *>, 8> >'; did you mean 'std::reverse_iterator'?
  Range<ArgIndexInstMapTy::reverse_iterator>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        std::reverse_iterator
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:529:29: note: 'std::reverse_iterator' declared here
class _LIBCPP_TYPE_VIS_ONLY reverse_iterator
                            ^
/Users/erik/proj/main-swift/swift/lib/SILPasses/FunctionSignatureOpts.cpp:125:9: error: use of class template 'ArgIndexInstMapTy::reverse_iterator' requires template arguments
  Range<ArgIndexInstMapTy::reverse_iterator>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:529:29: note: template is declared here
class _LIBCPP_TYPE_VIS_ONLY reverse_iterator
                            ^
/Users/erik/proj/main-swift/swift/lib/SILPasses/FunctionSignatureOpts.cpp:127:12: error: no matching function for call to 'reversed'
    return reversed(ConsumedArgumentIndexToReleaseMap);
           ^~~~~~~~
/Users/erik/proj/main-swift/swift/include/swift/Basic/Range.h:62:15: note: candidate template ignored: substitution failure [with T = llvm::MapVector<unsigned int, swift::SILInstruction *, llvm::SmallDenseMap<unsigned int, unsigned int, 8, llvm::DenseMapInfo<unsigned int> >, llvm::SmallVector<std::__1::pair<unsigned int, swift::SILInstruction *>, 8> > &]: no member named 'rbegin' in 'llvm::MapVector<unsigned int, swift::SILInstruction *, llvm::SmallDenseMap<unsigned int, unsigned int, 8, llvm::DenseMapInfo<unsigned int> >, llvm::SmallVector<std::__1::pair<unsigned int, swift::SILInstruction *>, 8> >'
  inline auto reversed(T &&container)
              ^
3 errors generated.



Swift SVN r22965