relocate CPython install directory
It was being installed to a place where swift couldn't find it, causing this
error:
```
  1> import Python
error: repl.swift:1:8: error: missing required module 'CPython'
import Python
       ^
```

Initially, we thought this only happened on the Linux build, but I tried it out
on Mac and got the same problem. I verified that this fix fixes it on both.

I also removed the iterations over the target and arch because nothing in the
loop body uses those variables any more.

PiperOrigin-RevId: 193453576