[Build System] Remove tvOS i386 slice from compiler-rt lib
To fix this issue:
ld: building for tvOS, but linking in object file built for tvOS Simulator, file '/tmp/strip.rgKCdx' for architecture i386
fatal error: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: internal link edit command failed

rdar://70443440
(cherry picked from commit cc542c0f10f9a0848bfe94d1040d779ad1d6ec67)