Several changes:  - Introduce attribute modifiers, like $tensor.  - Make the diagnostics that happen when non-contant values are passed in as    attributes have good source location information, e.g. like this:
t.swift:15:13: error: attribute 'keep_dims' requires a constant argument
  let z = x.mean(alongAxes: 1,2,3, keepingDimensions: someBool)
          ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   it would be better to talk about the parameter the op function uses instead
   of the internal attribute name, but it isn't clear what that will take.  For
   now, this will suffice.
 - Eliminate the now-unnecessary "c" and "d" tensor constraints, since we can
   now model them with attributes.
 - Remove the vestiges of the old __tf_init_scalar function, which got
   removed a long time ago.

PiperOrigin-RevId: 184245393