implement SILGen support for 'defer' statement.  The only missing piece now is Sema support for detecting invalid exits out of defer bodies.  That said, SILGen will also detect it, and produce an error if sema misses something, e.g.:
t.swift:11:23: error: defer statement is not allowed to be exited
  while false { defer { break } }
                      ^
t.swift:12:9: error: defer statement is not allowed to be exited
  defer { return }
        ^

we should still diagnose these in Sema for better QoI of course.

This wraps up: <rdar://problem/17302850> Add a defer keyword to swift



Swift SVN r27760