When we lex an invalid leftbound dot, instead of emitting an error and swallowing it silently, have the lexer return it as an unknown token.  Enhance the expr parser to detect these things and squash any expression in progress into an ErrorExpr.  This allows us to silence really bad downstream errors.  For example, on:
struct S { func f() {} }
func f() {
  _ = S.
}

we formerly produced:

 x.swift:5:8: error: expected member name following '.'
 x.swift:5:7: error: expected member name or constructor call after type name
 x.swift:5:7: note: add arguments after the type to construct a value of the type
 x.swift:5:7: note: use '.self' to reference the type object

we now emit just the first one.  This fixes:
<rdar://problem/22290244> QoI: "UIColor." gives two issues, should only give one