[Lexer] Trim comments off operator-identifier before tokenize
Previously, builtin operators followed by comment block were tokenized as
normal operators (e.g. tok::oper_binary_spaced) instead of dedicated
token(e.g. tok::equal).
That used to cause strange parse errors:

  test.swift:1:3: error: use of unresolved operator '='
  _ =/* */2
    ^