Revert "New value types for Calendar, TimeZone, and Locale"
This reverts commit 46a9f5732976fdd6c2716c7389f5a3859235f85b.

This broke Swift CI, OSS incremental RA:

./swift/stdlib/public/SDK/Foundation/TimeZone.swift:228:45: error: 'NSTimeZone' is not implicitly convertible to 'TimeZone'; did you mean to use 'as' to explicitly convert?
        return lhs._wrapped.isEqual(to: rhs._wrapped)