[Parse] Support importing operator functions
Support:

  import func SomeModule.<->

Previously, you were required to write like:

  import func SomeModule . <->

Otherwise:

error: expected module name in import declaration
import func SomeFunc.<->
            ^
error: expected module name in import declaration
import func SomeFunc .<->
            ^
error: extraneous whitespace after '.' is not permitted
import func SomeFunc. <->
                    ^~