Disabled tests failing from missing objc symbol.
Two tests are currently failing with

dyld: lazy symbol binding failed: Symbol not found: _objc_opt_self
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_opt_self
  Expected in: /usr/lib/libobjc.A.dylib

Here, they are disabled for now.

rdar://problem/61345988