[test] Fix test failure due to C attribute position
The `stable/20250601` Clang apparently wants an attributed parameter to
have a name, and that the attributes follow the name:

```
/Users/alatsis/Desktop/rebranch/swift/test/Interop/C/swiftify-import/Inputs/counted-by-lifetimebound.h:7:76: error: 'lifetimebound' attribute only applies to parameters and implicit object parameters
int * __counted_by(len) simple(int len, int len2, int * __counted_by(len2) __lifetimebound p);
                                                                           ^
/Users/alatsis/Desktop/rebranch/swift/test/Interop/C/swiftify-import/Inputs/counted-by-lifetimebound.h:5:40: note: expanded from macro '__lifetimebound'
                                       ^
```

Also humor the compiler here:

```
 3 | #define __counted_by(x) __attribute__((__counted_by__(x)))
   |                                                       `- note: expanded from macro '__counted_by'
 4 | #define __counted_by_or_null(x) __attribute__((__counted_by_or_null__(x)))
 5 | #define __lifetimebound __attribute__((lifetimebound))
   :
22 | int * __counted_by(len) noncountedLifetime(int len, int * p __lifetimebound);
23 |
24 | int * __counted_by(13) _Nullable constant(int * _Nullable p __counted_by(13) __lifetimebound);
   |                                                                          `- error: combining '__counted_by' with non-zero count (which cannot be null) and '_Nullable'; did you mean '__counted_by_or_null' instead?
```