Revert "New value types for Calendar, TimeZone, and Locale"
This reverts commit 9c1f21bdf0d52d7c6f64f93df84e1c22f4c70303.

This breaks swift-ci for everyone:

stdlib/public/SDK/Foundation/Calendar.swift:426:74: error: 'DateInterval' is only available on iOS 10.0 or newer
    public func dateInterval(of component: Component, for date: Date) -> DateInterval? {