Added a short-term fix for string literals used in tfop attrs (#17546)
* String literals (used as tfop attrs) are again getting different SIL code
pattern, causing the infamous
/usr/local/google/home/hongm/ssd_part/git/swift-tensorflow-merge/swift/test/TensorFlowRuntime/tensor.swift:263:13: error: attribute 'padding' requires a constant argument
  let y = x.convolved2D(withFilter: filter, strides: (1, 1, 1, 1),

Filed https://bugs.swift.org/browse/SR-8117 for it, which should go away once we
move the partition pass to be right after deabstraction.

The short-term fix here is to avoid using small strings, so that compiler
will *not* generate the _StringObject.init(_smallUTF8SecondWord:) call.

This is done by disabling (comment out) the small string optimization code path in the 4 lines of code here https://github.com/apple/swift/blob/ad7cbb3a9324ff3ec99063f2174294feae420c28/stdlib/public/core/String.swift#L832-L835. 

Also tried an alternative suggested by rxwei@, where we pad the string literal
at the end of deabstraction pass, and remove the padding when lowering the insts
to TF ops. Unfortunately it did not work out -- for device string literals, even
after we pad with 16+ bytes (e.g. pad "/device:CPU:0" into
"________________/device:CPU:0"), _StringObject.init(_smallUTF8SecondWord:) is
still generated somehow.

Also renamed the device pseudo-attr from "device" to "__device", for consistency
with "__shapes".

The only test failure is now TensorFlow/tensor_autodiff.swift.

The remaining limitation is that an empty string literal is not supported. This
support of empty string attrs is not currently needed in any existing ops (as
far as unti test coverage is concerned), and can be added via more short-term
hacks if needed.

The empty string case generates a new SIL code pattern as follows, where the
_StringObject struct, when representing an empty string, no longer points to a
string_literal eventually, and instead sets its second operand (%5 in the
example below) to 0.

  %0 = integer_literal $Builtin.Int64, 0          // user: %5
  %1 = integer_literal $Builtin.Int64, -2305843009213693952 // user: %2
  %2 = struct $UInt (%1 : $Builtin.Int64)         // user: %3
  %3 = value_to_bridge_object %2 : $UInt          // user: %4
  %4 = struct $_StringObject (%3 : $Builtin.BridgeObject) // user: %6
  %5 = struct $UInt (%0 : $Builtin.Int64)         // user: %6
  %6 = struct $_StringGuts (%4 : $_StringObject, %5 : $UInt) // user: %7
  %7 = struct $String (%6 : $_StringGuts)         // users: %49, %49
  %49 = builtin "__tfop_OneShotIterator,container,dataset_factory,output_types,output_shapes,shared_name"(%7 : $String, %8 : $@convention(tensorflow) () -> @owned VariantHandle, %21 : $Array<Float.Type>, %32 : $Array<TensorShape>, %7 : $String) : $ResourceHandle // users: %85, %77, %51, %50
  debug_value %49 : $ResourceHandle, let, name "iterator" // id: %50

* After doing a
./utils/update-checkout --scheme tensorflow --skip-repository swift

tensorflow stdlib no longer compiles. Fixed the build.