Fix AllocBoxToStack to recognize mark_dependence
This supports non-Copyable containers that vend a non-Escapable view such as a Span:

  let parent = NonCopyableParent()
  let value = parent.view.getNonCopyableValue()
  _ = consumeParent(parent)
  _ = consume value

Without this, the move-checker completely fails to analyze the lifetime of 'parent' and reports a non-Copyable violation:

ERROR: noncopyable 'parent' cannot be consumed when captured by an escaping closure or borrowed by a non-Escapable type

Fixes rdar://171519871 (Cannot consume noncopyable because value still borrowed by unreachable nonescapable)