Improve logging in `swift_build_support/shell.py` (#74592)
Currently, when a command fails with this message 

```
ERROR: command terminated with a non-zero exit status 1, aborting
```

it's unclear at all which exact command terminated, which makes it very hard to debug issues in the build script.