[build-script] Handle SystemExit containing string error messages
Sometimes we set `SystemExit.code` to a string. In such cases
the build-script would throw another exception when handling
`SystemExit` because `os._exit` expects an integer input:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"/Users/ec2-user/jenkins/workspace/oss-lldb-asan-macos/swift/utils/build-script",
line 722, in <module>
    os._exit(e.code)
TypeError: an integer is required (got type str)
```

Looks like we're setting `SystemExit.code` to a string error message
sometimes.
```

This patch handles such cases by checking the type of `SystemExit.code` before
calling `os._exit`