Add fixit hint to migrate code from the old unicode escapes to the new one:
swift x.swift
x.swift:3:15: error: unicode escapes changed, please use the \u{42} syntax instead
var x = "foo \x42 \u1234 \U12345678"
              ^~~~
              u{42}
x.swift:3:20: error: unicode escapes changed, please use the \u{1234} syntax instead
var x = "foo \x42 \u1234 \U12345678"
                   ^~~~~~
                   u{1234}
x.swift:3:27: error: unicode escapes changed, please use the \u{12345678} syntax instead
var x = "foo \x42 \u1234 \U12345678"
                          ^~~~~~~~~~
                          u{12345678}

No testcase since this is all temporary anyway.



Swift SVN r19449