introduce a "diagnose" forwarding helper function on the FailureDiagnosis class to avoid having to use CS->TC.diagnose everywhere.
Also, change SubscriptExpr diagnostics to put the caret on the [ of the subscript
instead of at the start of the base expression.  For example, instead of:

error: cannot subscript a value of type '[Int]?'
    return foo.array[0]
           ^~~~~~~~~
emit:

error: cannot subscript a value of type '[Int]?'
    return foo.array[0]
           ~~~~~~~~~^



Swift SVN r30318