Don't forward @main into SIL
We've already generated the parts necessary to handle `@main` during
SILGen. Keeping the attribute on the struct means that re-ingesting the
SIL will fail because it tries to re-create the implicit `$main`
function resulting in the following error message:

error: invalid redeclaration of synthesized static method '$main()'
  static func $main()