Diagnose inverse-existential casts that need a newer runtime
Six casting tests fail on macOS 10.15 with

    dyld: Symbol not found: _swift_getExtendedExistentialTypeMetadata_unique

Non-copyable or non-escapable existentials must use _extended_ existentials,
since plain existentials cannot represent suppressed protocols.
This specifically affects casts of such values, which require
correct metadata to be emitted.

The casting metadata generation was fixed recently, which caused some
casting tests to start failing in back-deployment because extended
existentials only started being supported in the Swift 5.7 (macOS 13.0)
runtime.

This is still subtly broken between Swift 5.7 (when extended/parameterized
existentials were added) and Swift 6.0 (when those existentials learned about
inverted protocols).  This change does not touch the behavior within that
range.

This PR also disables back-deployment testing of three COM tests which
require new runtime support.