significantly improve the QoI of the definitive initialization check by printing the variable being used and the access path to the uninitialized field (if relevant).
For example, for:

func test3() {
  var s2 : ((Int, Int), (), SomeStruct, Int)
  s2.0 = (1,2)
  s2.2.x = 1
  s2.2.z = 1
  s2.3 = 17337
  noop(s2)
}

we now produce:

t.swift:12:8: error: variable 's2.2.y' used before being initialized
  noop(s2)
       ^
t.swift:7:7: note: variable defined here
  var s2 : ((Int, Int), (), SomeStruct, Int)
      ^




Swift SVN r7140