fix S4TF test suite instructions in readme
I tried to test out the test instructions and encountered some problems.

First problem: build-script does a debug build by default, and this fails for
me with
"/home/marcrasi/swift-build-script-debug/swift/lib/Basic/Statistic.cpp:477:
error: undefined reference to 'swift::UnifiedStatsReporter::TraceFormatter
const* swift::FrontendStatsTracer::getTraceFormatter<swift::SILFunction
const*>()'". This seems like a problem we should deal with eventually, but we
can circumvent it in the test suite instructions by telling people to run the
test suite with "--release-debuginfo".

Second problem: Apparently there is some known issue with the swift tests where
some of them fail unless you configure assertions in a very particular way
(https://github.com/apple/swift/commit/7333c1995f94de431daa88942cceacf2d850c335).
So I added some flags configuring those assertions.

And a third thing: We need `--test-optimized` for it to run the TensorFlowRuntime tests, because those only run with optimization enabled.

I have tested this new invocation on Linux and it succeeds. I'm currently
running it on Mac too.

PiperOrigin-RevId: 194464995