fix <rdar://problem/20489838> QoI: Nonsensical error and fixit if "let" is missing between 'if let ... where' clauses
by tweaking parsing logic to handle a common error case with a nice diagnostic + fixit.  We now produce:

x.swift:4:29: error: binding ended by previous 'where' clause; use 'let' to introduce a new one
if let y? = x where y == 0, z? = x where z == 0 {
                            ^
                            let 



Swift SVN r27452