Basic: make the member specifiers match the declaration
Visual Studio does not like the member being declared as `const` and then used
as `constexpr`.

  include\swift\Basic\ImmutablePointerSet.h(352): error C2370: 'swift::ImmutablePointerSetFactory<T>::AllocAlignment': redefinition; different storage class
  include\swift\Basic\ImmutablePointerSet.h(185): note: see declaration of 'swift::ImmutablePointerSetFactory<T>::AllocAlignment'
  include\swift\Basic\ImmutablePointerSet.h(352): error C2059: syntax error: '='
  include\swift\Basic\ImmutablePointerSet.h(353): error C2059: syntax error: 'alignof'

Hoist this into a templated class to make it a dependent type to delay the
evaluation.