[Type checker] Don't infer 'dynamic' for 'let' variables or within final classes.
The 'dynamic' inference would infer 'dynamic' in places where it would
also infer 'final', leading to a diagnostic

  error: a declaration cannot be both 'final' and 'dynamic'

with no source location information. Don't infer 'dynamic' in such
places. Fixes SR-993 / rdar://problem/20449627.

(cherry picked from commit 81661262c8f4d124cce4c9b1897cfb516a52b165)