fix ConstructorDecl::getDelegatingOrChainedInitKind to notice that an init method has the convenience attribute on it when inferring the type of an init that contains no self.init or super.init method.  This allows us to properly infer that these things are delegating initializers, which trickles down to emitting:
a.swift:7:3: error: self.init isn't called on all paths in delegating initializer

for:

  required convenience init(foo: Int) {
  }

instead of doing DI as though the initializer was a root init.



Swift SVN r21120