Prepare for strict enforcement of conditionally Escapable
The only intended functional change is that a diagnostic message is split into
an error and a note:

    error: cannot copy the lifetime of an Escapable type
    note: use '@_lifetime(borrow arg)' instead

Reorganize the LifetimeDependenceChecker to support adding the functionality
required for strict enforcement.

Adds parameter index to ParamInfo.

Adds a few (temporarily unused) helper methods.