Add Builtin.hopToActor to the feature list.
Builtin.hopToActor was introduced after branching 5.5. It's
availability is 5.5 because the compiler's version has not been bumped
on the dev branch. Therefore, cherry-pick the feature back to 5.5 in
case the 5.5 compiler is used to parse a newer Concurrency library.

Fixes rdar://80525569 error: module 'Builtin' has no member named 'hopToActor')