[cxx-interop] Modularize __msvc_string_view on Windows
`__msvc_string_view.hpp` header was added in a recent MSVC version. It should be referenced directly from the STL modulemap to make sure it doesn't get hijacked by an unexpected Clang module that happened to be processed first by Clang.

This fixes a test failure that started triggering in CI after MSVC version upgrade:
```
C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\swift\test\Interop\Cxx\stdlib/Inputs\std-string-view.h:3:13: error: missing '#include <__msvc_string_view.hpp>'; 'string_view' must be declared before it is used
```

This is similar to 16e7cbea.

rdar://144385377