[Parse] Normal error message for standalone 'protocol' in type position
instead of 'expected identifier for type name', as the same as:

  x.swift:1:13: error: expected parameter type following ':'
  func foo(x: struct) {}
              ^