Don’t cross-compile sourcekit-lsp and indexstore-db when running tests
Running swift test with `--test-product SourceKitLSPPackageTest` fails when cross-compiling with an error message like the following (rdar://97876450)
```
error: Could not find target named 'SourceKitLSPPackageTests_-6F17C3BE20775DA1_PackageProduct'
```

Since we don’t run the test on the cross-compile host anyway, just disable cross-compilation during testing.