Fix rdar://19710848 QoI: Friendlier error message for "[] as Set"
This makes diagnoseGeneralConversionFailure more conservative: it
now never diagnoses a failed conversion when it involves a type that
has unresolved type in it.  These types could not be resolved, so it
is better to let ambiguity resolution handle the problem.

On "[] as Set", we would previously get:
  error: 'Set<_>' is not convertible to 'Set<Element>'
now we get:
  error: generic parameter 'Element' could not be inferred