Remove Builtin.borrowAt usage from the standard library
This builtin cannot be used inside inlinable functions without a feature
guard. It is needed for ~Escapable elements. Guarding the uses with a feature
flag will, however, be quite cumbersome. Let's hope that by the time we need ~E
elements, the oldest relevant toolchain has support for this builtin.

Fixes rdar://178659021 (condfail: error: module 'Builtin' has no member named
'borrowAt')

(cherry picked from commit 921f59e32ce18c38f9e091d85ac9fa039eae180e)