X86: bump the minimum required CPU to IvyBridge
Bump the minimum supported CPU to IvyBridge so that we can take
advantage of the F16C/CVT16 extensions to support half floating point
rounding.  This avoids the undefined reference to `__extendsfhf2` in the
FP16 support.