Forward -sanitize flags to -compile-module-from-interface subinvocations
\#88564 started passing fsanitize flags to the clang importer. This means
that compliations via the clang importer may use different LangOpts
or target features (e.g. +mte for `-sanitize memtag-stack`).

I ran into an issue where it appears that `-sanitize memtag-stack` and its
implied +mte target feature are not being uniformly applied. This causes
PCMs to be rejected:

```
error: precompiled file '<redacted>' was compiled with the target feature '+mte'
but the current translation unit is not
```

It looks like this is because -sanitize options are not inherited in
`InterfaceSubContextDelegateImpl::inheritOptionsForBuildingInterface`.

rdar://185067740