When evaluating candidates for closeness, make sure to consider UnresolvedType to be a match, since it *could* be, and typically conforms to whatever the expression is.
Fixing this improves the diagnostic in Constraints/closures.swift significantly, and
fixes these bugs:
<rdar://problem/21718970> QoI: [uninferred generic param] cannot invoke 'foo' with an argument list of type '(Int)'
<rdar://problem/21718955> Swift useless error: cannot invoke 'foo' with no arguments

where before we produced:
error: cannot invoke 'foo' with an argument list of type '(Int)'

and now produce:

x.swift:5:10: error: generic parameter 'A' could not be inferred
Whatever.foo(a: 23)
         ^
x.swift:1:7: note: 'A' declared as parameter to type 'Whatever'
class Whatever<A: IntegerArithmetic, B: IntegerArithmetic> {
      ^