Fix Windows build
```
S:\jenkins\workspace\swift-PR-windows\swift\stdlib\public\Concurrency\Actor.cpp(1612,22): error: expected unqualified-id
              : std::max(oldPriority, job->getPriority());
                     ^
C:\Program Files (x86)\Windows Kits\10\\Include\10.0.18362.0\shared\minwindef.h(193,29): note: expanded from macro max
#define max(a,b)            (((a) > (b)) ? (a) : (b))
                            ^
1 error generated.
```

(cherry picked from commit 28a23e5b415c355286613f20cc86b580874529c3)