Run optimization and partitioning passes for compiler-integrated REPL.
These passes are run for the LLDB-enabled REPL, but not for the
compiler-integrated one.

Partially addresses https://github.com/google/swift/issues/8.
Initializing `Tensor`s still fails because the hard-coded REPL filename
contains invalid characters:

  (swift) import TensorFlow
  (swift) let x = Tensor(1)
  ...
  Fatal error: Node 'op.<REPL Input>.1.16': Node name contains invalid characters

PiperOrigin-RevId: 195028482