Guard lifetime dependence diagnostics
by -enable-experimental-feature NonescapableTypes

These passes do nothing unless the above feature flag is enabled, so
there's no reason to be running them.

These passes rely on fundamental SwiftCompilerSources abstractions
which have not yet been tested outside of the passes. They don't yet
handle all SIL patterns, and SIL continues to evolve. We should not
expose these issues on a release branch.

This reverts commit 6efcb595b0731dfe34cf384ad52aac95d4b79106.
"Always-enable lifetime-depenence diagnostics."

Workaround for:

** rdar://129931868 [nonescapable] (Crash on attempt to compile unit
   test); SIL/FunctionConvention.swift:29: Fatal error: requires
   contextual type

** rdar://129494573 [nonescapable] [LifetimeDependenceDiagnostics]

** rdar://128434000 ([nonescapable] [LifetimeDependenceInsertion] Package resolution fails with arm64 Windows toolchain)