Fix a move checker use-after-free: insert destroy_addr before reinit
Fixes patterns involving MutableSpan reassignment that were previously
miscompiled, compromising memory safety. For example:

  var ms = MutableSpan<Int>()
  useSpan(ms)

  do {
    var ua = UniqueArray()
    ms = ua.mutableSpan
  }
  useSpan(ms)

This is now correctly diagnosed as:
error: lifetime-dependent variable 'ms' escapes its scope

The move checker previously generated invalid SIL patterns in which destroy_addr
was inside an access scope:

  %0 = alloc_stack [lexical] [var_decl] $MutableSpan<Int>, var, name "ms", type $MutableSpan<Int>
  ...
  %access = begin_access [modify] [static] %0
  destroy_addr %0
  store %val to [init] %access
  end_access %access

This is obviously invalid SIL, but it was not caught by SIL verification because
we don't yet have access scope verification. See rdar181649181 (Need SIL memory
verification for access scopes).

Fixes rdar://161667945 ([nonescapable] [miscompile] Reassignment does not change
lifetime constraint of binding)