Improve struct declarations to use their TypeAlias for the constructor results.  In the testcase we now get: error: cannot convert initializer type 'CGPoint' to explicitly specified type 'int'   var d : int = CGPoint(.y = 1, .x = 2);   // Using injected name.                 ^
instead of:
error: cannot convert initializer type 'oneof { CGPoint : (x : int, y : int)}' to explicitly specified type 'int'
  var d : int = CGPoint(.y = 1, .x = 2);   // Using injected name.
                ^


Swift SVN r298