[update_checkout] Improved validation failure diagnostic.
Previously, if an alias were defined for multiple schemes, the produced
diagnostic would only say that there was a collision, but did not
specify where that collision was.  Here, the diagnostic is improved to
read

    RuntimeError: Configuration file defines the alias ALIAS in both the
                  SCHEME_NAME_1 scheme and the SCHEME_NAME_2 scheme?!