fix <rdar://problem/15685991> QoI: Missing leading zero in floating point literal should have a FixIt
Before we produced:
t.swift:4:12: error: expected identifier after '.' expression
  let x = .42
           ^
t.swift:4:7: error: type annotation missing in pattern
  let x = .42
      ^

now we produce:

t.swift:4:11: error: '.42' is not a valid floating point literal; it must be written '0.42'
  let x = .42
          ^~~
          0



Swift SVN r26404